source 'https://rubygems.org'

# fixing the ruby version
ruby '2.3.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5.1'
gem 'rake'

# action mailer for sending the emails
gem 'actionmailer'
# devise for authentication
gem 'devise'
# Use pg as the database for Active Record
gem 'pg'
# for json response https://github.com/rails-api/active_model_serializers
gem "active_model_serializers", '~> 0.8.3'
# Use ActiveModel has_secure_password
gem 'bcrypt'

# Use thin as the app server
gem 'thin'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.1'

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc


# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end


